# Generated by Django 5.2.17 on 2026-09-27 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=200)),
                ('anamnese', models.TextField(help_text='Texto das anotações de anamnese enviadas pela psicóloga.')),
                ('arquivo_nome', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('usuaria', 'Usuária'), ('ia', 'IA')], max_length=10)),
                ('texto', models.TextField(blank=True)),
                ('erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='laudos.laudo')),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Paragrafo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('trajetoria_escolar', 'Trajetória escolar e acadêmica'), ('cognicao', 'Memória, atenção e aprendizagem'), ('rotina', 'Rotina, organização, rigidez e perfeccionismo'), ('comportamento', 'Hiperatividade, impulsividade e comportamento'), ('interesses', 'Interesses e lazer'), ('sensorial', 'Sensibilidade sensorial'), ('social', 'Vida social'), ('relacionamentos', 'Relacionamentos afetivos e familiares'), ('humor', 'Humor e regulação emocional'), ('ansiedade', 'Ansiedade'), ('alimentacao', 'Alimentação e imagem corporal'), ('sono', 'Sono'), ('outro', 'Outro tema'), ('saude', '- Saúde'), ('medicacao', '- Uso de Medicação'), ('historico_familiar', '- Histórico Familiar'), ('profissionais', '- Profissional que acompanha')], max_length=40)),
                ('posicao', models.PositiveIntegerField(default=0, help_text='Ordem entre parágrafos do mesmo tema.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragrafos', to='laudos.laudo')),
            ],
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('texto', models.TextField()),
                ('trechos_origem', models.JSONField(blank=True, default=list)),
                ('origem', models.CharField(choices=[('geracao', 'Gerado pela IA'), ('ajuste', 'Ajuste pedido na conversa'), ('revisao', 'Revisão de texto da usuária'), ('edicao_usuaria', 'Editado pela usuária')], max_length=20)),
                ('faltou', models.JSONField(blank=True, default=list)),
                ('sem_apoio', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('mensagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes', to='laudos.mensagem')),
                ('paragrafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='laudos.paragrafo')),
            ],
            options={
                'ordering': ['paragrafo_id', 'numero'],
                'unique_together': {('paragrafo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Exemplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('trajetoria_escolar', 'Trajetória escolar e acadêmica'), ('cognicao', 'Memória, atenção e aprendizagem'), ('rotina', 'Rotina, organização, rigidez e perfeccionismo'), ('comportamento', 'Hiperatividade, impulsividade e comportamento'), ('interesses', 'Interesses e lazer'), ('sensorial', 'Sensibilidade sensorial'), ('social', 'Vida social'), ('relacionamentos', 'Relacionamentos afetivos e familiares'), ('humor', 'Humor e regulação emocional'), ('ansiedade', 'Ansiedade'), ('alimentacao', 'Alimentação e imagem corporal'), ('sono', 'Sono'), ('outro', 'Outro tema'), ('saude', '- Saúde'), ('medicacao', '- Uso de Medicação'), ('historico_familiar', '- Histórico Familiar'), ('profissionais', '- Profissional que acompanha')], max_length=40)),
                ('trecho_origem', models.TextField(blank=True)),
                ('texto', models.TextField()),
                ('fonte', models.CharField(choices=[('laudo_base', 'Laudo base'), ('like', 'Like')], max_length=20)),
                ('grupo', models.CharField(blank=True, help_text='Laudo base de onde veio o exemplo.', max_length=100)),
                ('posicao', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('versao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exemplo', to='laudos.versao')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('like', 'Like'), ('deslike', 'Deslike')], max_length=10)),
                ('motivos', models.JSONField(blank=True, default=list)),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='laudos.versao')),
            ],
        ),
    ]
