# Generated by Django 5.2.17 on 2026-09-27 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplo',
            name='dono',
            field=models.ForeignKey(blank=True, help_text='Quem aprovou o exemplo. Vazio nos laudos base, que valem para todas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exemplos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laudo',
            name='dono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laudos', to=settings.AUTH_USER_MODEL),
        ),
    ]
