# Generated by Django 5.2.17 on 2026-09-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laudos', '0002_dono'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplo',
            name='secao',
            field=models.CharField(choices=[('2', '2. DESCRIÇÃO DA DEMANDA'), ('4.2', '4.2 DADOS DA ENTREVISTA DE ANAMNESE'), ('5.1', '5.1 CONCLUSÃO: RELAÇÃO ENTRE OS INSTRUMENTOS E OS RELATOS'), ('5.2', '5.2 CONCLUSÃO: HIPÓTESES DIAGNÓSTICAS'), ('6', '6. RECOMENDAÇÕES E ENCAMINHAMENTOS')], default='4.2', max_length=5),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='secao',
            field=models.CharField(choices=[('2', '2. DESCRIÇÃO DA DEMANDA'), ('4.2', '4.2 DADOS DA ENTREVISTA DE ANAMNESE'), ('5.1', '5.1 CONCLUSÃO: RELAÇÃO ENTRE OS INSTRUMENTOS E OS RELATOS'), ('5.2', '5.2 CONCLUSÃO: HIPÓTESES DIAGNÓSTICAS'), ('6', '6. RECOMENDAÇÕES E ENCAMINHAMENTOS')], default='4.2', max_length=5),
        ),
        migrations.AddField(
            model_name='paragrafo',
            name='secao',
            field=models.CharField(choices=[('2', '2. DESCRIÇÃO DA DEMANDA'), ('4.2', '4.2 DADOS DA ENTREVISTA DE ANAMNESE'), ('5.1', '5.1 CONCLUSÃO: RELAÇÃO ENTRE OS INSTRUMENTOS E OS RELATOS'), ('5.2', '5.2 CONCLUSÃO: HIPÓTESES DIAGNÓSTICAS'), ('6', '6. RECOMENDAÇÕES E ENCAMINHAMENTOS')], default='4.2', max_length=5),
        ),
        migrations.AlterField(
            model_name='exemplo',
            name='tema',
            field=models.CharField(choices=[('abertura', 'Abertura'), ('alimentacao', 'Alimentação e imagem corporal'), ('ansiedade', 'Ansiedade'), ('atividades', 'Atividades do dia a dia'), ('cognicao', 'Memória, atenção e aprendizagem'), ('comportamental_emocional', 'Aspectos comportamentais e emocionais'), ('comportamento', 'Hiperatividade, impulsividade e comportamento'), ('contraste', 'Testes e rotina'), ('demanda', 'Descrição da demanda'), ('diagnostico', 'Diagnóstico ou hipótese'), ('escola', 'Escola'), ('fechamento', 'Fechamento'), ('hipotese_descartada', 'Hipótese descartada'), ('historico_familiar', '- Histórico Familiar'), ('humor', 'Humor e regulação emocional'), ('integracao', 'Integração dos achados'), ('interesses', 'Interesses e lazer'), ('medicacao', '- Uso de Medicação'), ('observacao', 'Observação final'), ('outras_especialidades', 'Outros profissionais'), ('outras_medicas', 'Outras especialidades médicas'), ('outro', 'Outro ponto'), ('profissionais', '- Profissional que acompanha'), ('psicologia', 'Psicologia'), ('psiquiatria', 'Psiquiatria'), ('reavaliacao', 'Reavaliação'), ('relacionamentos', 'Relacionamentos afetivos e familiares'), ('rotina', 'Rotina, organização, rigidez e perfeccionismo'), ('saude', '- Saúde'), ('sensorial', 'Sensibilidade sensorial'), ('social', 'Aspectos sociais'), ('sono', 'Sono'), ('trajetoria_escolar', 'Trajetória escolar e acadêmica')], max_length=40),
        ),
        migrations.AlterField(
            model_name='paragrafo',
            name='tema',
            field=models.CharField(choices=[('abertura', 'Abertura'), ('alimentacao', 'Alimentação e imagem corporal'), ('ansiedade', 'Ansiedade'), ('atividades', 'Atividades do dia a dia'), ('cognicao', 'Memória, atenção e aprendizagem'), ('comportamental_emocional', 'Aspectos comportamentais e emocionais'), ('comportamento', 'Hiperatividade, impulsividade e comportamento'), ('contraste', 'Testes e rotina'), ('demanda', 'Descrição da demanda'), ('diagnostico', 'Diagnóstico ou hipótese'), ('escola', 'Escola'), ('fechamento', 'Fechamento'), ('hipotese_descartada', 'Hipótese descartada'), ('historico_familiar', '- Histórico Familiar'), ('humor', 'Humor e regulação emocional'), ('integracao', 'Integração dos achados'), ('interesses', 'Interesses e lazer'), ('medicacao', '- Uso de Medicação'), ('observacao', 'Observação final'), ('outras_especialidades', 'Outros profissionais'), ('outras_medicas', 'Outras especialidades médicas'), ('outro', 'Outro ponto'), ('profissionais', '- Profissional que acompanha'), ('psicologia', 'Psicologia'), ('psiquiatria', 'Psiquiatria'), ('reavaliacao', 'Reavaliação'), ('relacionamentos', 'Relacionamentos afetivos e familiares'), ('rotina', 'Rotina, organização, rigidez e perfeccionismo'), ('saude', '- Saúde'), ('sensorial', 'Sensibilidade sensorial'), ('social', 'Aspectos sociais'), ('sono', 'Sono'), ('trajetoria_escolar', 'Trajetória escolar e acadêmica')], max_length=40),
        ),
    ]
